name: Build and Push Frontend Docker Image to Docker Hub

on:
    workflow_dispatch:

jobs:
  build-and-push-frontend-to-docker:
    runs-on: ubuntu-20.04  # Specify a known Ubuntu version

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Debug Docker environment
      - name: Debug Docker environment
        run: |
          docker version
          docker info

      # Step 3: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build Docker image for TestPrep Frontend
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/testprep_f:latest \
            -f frontend/Dockerfile frontend/

    # Step 5: Push Docker Image
      - name: Push Docker image to Docker Hub
        run: |
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/testprep_f:latest
  
  deploy:
    needs: build-and-push-frontend-to-docker
    runs-on: self-hosted
    steps:
      - name: Pull Docker image from Docker Hub
        run: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/testprep_f:latest
      - name: Run Docker container 
        run: |
            docker run -d -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/testprep_f:latest
        
